class endpoints:
    GetServers = "getservers"
    GetPrices = "getprices"
    GetAllServices = "getservices"
    GetServiceInfo = "getinfo"
    Changeprotocol = "changeprotocol"
    GetLinks = "getlinks"
    ChangeLinks = "changelink"
    AccInfo = "accountinfo"
    BuyMoreUser = "buymoreuser"
    Getconnections = "getconnections"
    ChangeName = "changename"
    Changelocation = "changelocation"
    Buymoretraffic = "buymoretraffic"
    buyservice = "buyservice"
    extensionservice = "extensionservice"
